// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package endpoint

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseBoolQueryFromString Parse BoolQuery from string
func ParseBoolQueryFromString(str string) (BoolQuery, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := BoolQuery_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown BoolQuery: %s", str)
	}

	return BoolQuery(v), nil
}

// Equal type compare
func (t BoolQuery) Equal(target BoolQuery) bool {
	return t == target
}

// IsIn todo
func (t BoolQuery) IsIn(targets ...BoolQuery) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t BoolQuery) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *BoolQuery) UnmarshalJSON(b []byte) error {
	ins, err := ParseBoolQueryFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
