//go:generate  mcube enum -m -p
//
// Code generated by protoc-gen-go-ext. DO NOT EDIT.
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: pkg/endpoint/pb/enum.proto

package endpoint

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoolQuery int32

const (
	// ALL todo
	BoolQuery_ALL BoolQuery = 0
	// Pending todo
	BoolQuery_TRUE BoolQuery = 1
	// Passed todo
	BoolQuery_FALSE BoolQuery = 2
)

// Enum value maps for BoolQuery.
var (
	BoolQuery_name = map[int32]string{
		0: "ALL",
		1: "TRUE",
		2: "FALSE",
	}
	BoolQuery_value = map[string]int32{
		"ALL":   0,
		"TRUE":  1,
		"FALSE": 2,
	}
)

func (x BoolQuery) Enum() *BoolQuery {
	p := new(BoolQuery)
	*p = x
	return p
}

func (x BoolQuery) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoolQuery) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_endpoint_pb_enum_proto_enumTypes[0].Descriptor()
}

func (BoolQuery) Type() protoreflect.EnumType {
	return &file_pkg_endpoint_pb_enum_proto_enumTypes[0]
}

func (x BoolQuery) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoolQuery.Descriptor instead.
func (BoolQuery) EnumDescriptor() ([]byte, []int) {
	return file_pkg_endpoint_pb_enum_proto_rawDescGZIP(), []int{0}
}

var File_pkg_endpoint_pb_enum_proto protoreflect.FileDescriptor

var file_pkg_endpoint_pb_enum_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x70,
	0x62, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6b, 0x65,
	0x79, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2a, 0x29,
	0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x4c, 0x4c, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x52, 0x55, 0x45, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x46, 0x41, 0x4c, 0x53, 0x45, 0x10, 0x02, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x2f, 0x6b, 0x65, 0x79, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_endpoint_pb_enum_proto_rawDescOnce sync.Once
	file_pkg_endpoint_pb_enum_proto_rawDescData = file_pkg_endpoint_pb_enum_proto_rawDesc
)

func file_pkg_endpoint_pb_enum_proto_rawDescGZIP() []byte {
	file_pkg_endpoint_pb_enum_proto_rawDescOnce.Do(func() {
		file_pkg_endpoint_pb_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_endpoint_pb_enum_proto_rawDescData)
	})
	return file_pkg_endpoint_pb_enum_proto_rawDescData
}

var file_pkg_endpoint_pb_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_endpoint_pb_enum_proto_goTypes = []interface{}{
	(BoolQuery)(0), // 0: keyauth.endpoint.BoolQuery
}
var file_pkg_endpoint_pb_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_endpoint_pb_enum_proto_init() }
func file_pkg_endpoint_pb_enum_proto_init() {
	if File_pkg_endpoint_pb_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_endpoint_pb_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_endpoint_pb_enum_proto_goTypes,
		DependencyIndexes: file_pkg_endpoint_pb_enum_proto_depIdxs,
		EnumInfos:         file_pkg_endpoint_pb_enum_proto_enumTypes,
	}.Build()
	File_pkg_endpoint_pb_enum_proto = out.File
	file_pkg_endpoint_pb_enum_proto_rawDesc = nil
	file_pkg_endpoint_pb_enum_proto_goTypes = nil
	file_pkg_endpoint_pb_enum_proto_depIdxs = nil
}
