// Code generated by protoc-gen-go-http. DO NOT EDIT.

package endpoint

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/keyauth.endpoint.EndpointService/DescribeEndpoint",
				FunctionName:     "DescribeEndpoint",
				Path:             "/endpoints/:id",
				Method:           "GET",
				Resource:         "endpoint",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{},
			},
			{
				GrpcPath:         "/keyauth.endpoint.EndpointService/QueryEndpoints",
				FunctionName:     "QueryEndpoints",
				Path:             "/endpoints",
				Method:           "GET",
				Resource:         "endpoint",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{},
			},
			{
				GrpcPath:         "/keyauth.endpoint.EndpointService/Registry",
				FunctionName:     "Registry",
				Path:             "/endpoints",
				Method:           "POST",
				Resource:         "endpoint",
				AuthEnable:       false,
				PermissionEnable: false,
				Labels:           map[string]string{},
			},
			{
				GrpcPath:         "/keyauth.endpoint.EndpointService/DeleteEndpoint",
				FunctionName:     "DeleteEndpoint",
				Path:             "/endpoints",
				Method:           "DELETE",
				Resource:         "endpoint",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{},
			},
			{
				GrpcPath:         "/keyauth.endpoint.EndpointService/QueryResources",
				FunctionName:     "QueryResources",
				Path:             "/resources",
				Method:           "GET",
				Resource:         "resource",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{},
			},
		},
	}
	return set
}
