// Code generated by protoc-gen-go-http. DO NOT EDIT.

package endpoint

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:              "/keyauth.endpoint.EndpointService/DescribeEndpoint",
				FunctionName:      "DescribeEndpoint",
				Method:            "GET",
				Resource:          "endpoint",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.endpoint.EndpointService/QueryEndpoints",
				FunctionName:      "QueryEndpoints",
				Method:            "GET",
				Resource:          "endpoint",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.endpoint.EndpointService/Registry",
				FunctionName:      "Registry",
				Method:            "POST",
				Resource:          "endpoint",
				AuthEnable:        false,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.endpoint.EndpointService/DeleteEndpoint",
				FunctionName:      "DeleteEndpoint",
				Method:            "DELETE",
				Resource:          "endpoint",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.endpoint.EndpointService/QueryResources",
				FunctionName:      "QueryResources",
				Method:            "GET",
				Resource:          "resource",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
		},
	}
	return set
}
