// Code generated by protoc-gen-go-http. DO NOT EDIT.

package domain

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:              "/keyauth.domain.DomainService/CreateDomain",
				FunctionName:      "CreateDomain",
				Method:            "POST",
				Resource:          "domain",
				AuthEnable:        true,
				PermissionEnable:  true,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"action": "create"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.domain.DomainService/UpdateDomain",
				FunctionName:      "UpdateDomain",
				Method:            "GET",
				Resource:          "domain",
				AuthEnable:        true,
				PermissionEnable:  true,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"action": "update"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.domain.DomainService/DescribeDomain",
				FunctionName:      "DescribeDomain",
				Method:            "GET",
				Resource:          "domain",
				AuthEnable:        true,
				PermissionEnable:  true,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"action": "get"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.domain.DomainService/QueryDomain",
				FunctionName:      "QueryDomain",
				Method:            "GET",
				Resource:          "domain",
				AuthEnable:        true,
				PermissionEnable:  true,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"action": "list"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.domain.DomainService/DeleteDomain",
				FunctionName:      "DeleteDomain",
				Method:            "DELETE",
				Resource:          "domain",
				AuthEnable:        true,
				PermissionEnable:  true,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"action": "delete"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.domain.DomainService/UpdateDomainSecurity",
				FunctionName:      "UpdateDomainSecurity",
				Method:            "PUT",
				Resource:          "domain",
				AuthEnable:        true,
				PermissionEnable:  true,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"action": "update"},
				Extension:         map[string]string{},
			},
		},
	}
	return set
}
