// Code generated by protoc-gen-go-http. DO NOT EDIT.

package endpoint

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:         "/keyauth.endpoint.EndpointService/DescribeEndpoint",
				FunctionName: "DescribeEndpoint",
			},
			{
				Path:         "/keyauth.endpoint.EndpointService/QueryEndpoints",
				FunctionName: "QueryEndpoints",
			},
			{
				Path:         "/keyauth.endpoint.EndpointService/Registry",
				FunctionName: "Registry",
			},
			{
				Path:         "/keyauth.endpoint.EndpointService/DeleteEndpoint",
				FunctionName: "DeleteEndpoint",
			},
			{
				Path:         "/keyauth.endpoint.EndpointService/QueryResources",
				FunctionName: "QueryResources",
			},
		},
	}
	return set
}
