// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package types

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseUserTypeFromString Parse UserType from string
func ParseUserTypeFromString(str string) (UserType, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := UserType_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown UserType: %s", str)
	}

	return UserType(v), nil
}

// Equal type compare
func (t UserType) Equal(target UserType) bool {
	return t == target
}

// IsIn todo
func (t UserType) IsIn(targets ...UserType) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t UserType) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *UserType) UnmarshalJSON(b []byte) error {
	ins, err := ParseUserTypeFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
