// Code generated by protoc-gen-go-http. DO NOT EDIT.

package session

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:         "/keyauth.session.UserService/Login",
				FunctionName: "Login",
			},
			{
				Path:         "/keyauth.session.UserService/Logout",
				FunctionName: "Logout",
			},
			{
				Path:              "/keyauth.session.UserService/DescribeSession",
				FunctionName:      "DescribeSession",
				Method:            "GET",
				Resource:          "session",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "audit_admin"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.session.UserService/QuerySession",
				FunctionName:      "QuerySession",
				Method:            "GET",
				Resource:          "session",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "audit_admin"},
				Extension:         map[string]string{},
			},
			{
				Path:         "/keyauth.session.AdminService/QueryUserLastSession",
				FunctionName: "QueryUserLastSession",
			},
		},
	}
	return set
}
