// Code generated by protoc-gen-go-http. DO NOT EDIT.

package user

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:         "/keyauth.user.UserService/QueryAccount",
				FunctionName: "QueryAccount",
			},
			{
				Path:         "/keyauth.user.UserService/DescribeAccount",
				FunctionName: "DescribeAccount",
			},
			{
				Path:         "/keyauth.user.UserService/CreateAccount",
				FunctionName: "CreateAccount",
			},
			{
				Path:         "/keyauth.user.UserService/BlockAccount",
				FunctionName: "BlockAccount",
			},
			{
				Path:         "/keyauth.user.UserService/UnBlockAccount",
				FunctionName: "UnBlockAccount",
			},
			{
				Path:         "/keyauth.user.UserService/DeleteAccount",
				FunctionName: "DeleteAccount",
			},
			{
				Path:         "/keyauth.user.UserService/UpdateAccountProfile",
				FunctionName: "UpdateAccountProfile",
			},
			{
				Path:         "/keyauth.user.UserService/UpdateAccountPassword",
				FunctionName: "UpdateAccountPassword",
			},
			{
				Path:         "/keyauth.user.UserService/GeneratePassword",
				FunctionName: "GeneratePassword",
			},
		},
	}
	return set
}
