// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: apps/verifycode/pb/verifycode.proto

package verifycode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Code todo
type Code struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: bson:"_id" json:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id"`
	// @gotags: json:"username" validate:"required"
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username" validate:"required"`
	// @gotags: json:"number" validate:"required"
	Number string `protobuf:"bytes,3,opt,name=number,proto3" json:"number" validate:"required"`
	// @gotags: bson:"issue_at" json:"issue_at"
	IssueAt int64 `protobuf:"varint,4,opt,name=issue_at,json=issueAt,proto3" json:"issue_at" bson:"issue_at"`
	// @gotags: bson:"expired_minite" json:"expired_minite"
	ExpiredMinite uint32 `protobuf:"varint,5,opt,name=expired_minite,json=expiredMinite,proto3" json:"expired_minite" bson:"expired_minite"`
}

func (x *Code) Reset() {
	*x = Code{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_verifycode_pb_verifycode_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Code) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Code) ProtoMessage() {}

func (x *Code) ProtoReflect() protoreflect.Message {
	mi := &file_apps_verifycode_pb_verifycode_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Code.ProtoReflect.Descriptor instead.
func (*Code) Descriptor() ([]byte, []int) {
	return file_apps_verifycode_pb_verifycode_proto_rawDescGZIP(), []int{0}
}

func (x *Code) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Code) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Code) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Code) GetIssueAt() int64 {
	if x != nil {
		return x.IssueAt
	}
	return 0
}

func (x *Code) GetExpiredMinite() uint32 {
	if x != nil {
		return x.ExpiredMinite
	}
	return 0
}

var File_apps_verifycode_pb_verifycode_proto protoreflect.FileDescriptor

var file_apps_verifycode_pb_verifycode_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x63, 0x6f, 0x64,
	0x65, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x2e, 0x6b, 0x65, 0x79, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x73, 0x73, 0x75, 0x65, 0x41, 0x74, 0x12, 0x25, 0x0a, 0x0e,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x4d, 0x69, 0x6e,
	0x69, 0x74, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6b, 0x65, 0x79,
	0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x63, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_verifycode_pb_verifycode_proto_rawDescOnce sync.Once
	file_apps_verifycode_pb_verifycode_proto_rawDescData = file_apps_verifycode_pb_verifycode_proto_rawDesc
)

func file_apps_verifycode_pb_verifycode_proto_rawDescGZIP() []byte {
	file_apps_verifycode_pb_verifycode_proto_rawDescOnce.Do(func() {
		file_apps_verifycode_pb_verifycode_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_verifycode_pb_verifycode_proto_rawDescData)
	})
	return file_apps_verifycode_pb_verifycode_proto_rawDescData
}

var file_apps_verifycode_pb_verifycode_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apps_verifycode_pb_verifycode_proto_goTypes = []interface{}{
	(*Code)(nil), // 0: infraboard.keyauth.verifycode.Code
}
var file_apps_verifycode_pb_verifycode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_verifycode_pb_verifycode_proto_init() }
func file_apps_verifycode_pb_verifycode_proto_init() {
	if File_apps_verifycode_pb_verifycode_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_verifycode_pb_verifycode_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Code); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_verifycode_pb_verifycode_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_verifycode_pb_verifycode_proto_goTypes,
		DependencyIndexes: file_apps_verifycode_pb_verifycode_proto_depIdxs,
		MessageInfos:      file_apps_verifycode_pb_verifycode_proto_msgTypes,
	}.Build()
	File_apps_verifycode_pb_verifycode_proto = out.File
	file_apps_verifycode_pb_verifycode_proto_rawDesc = nil
	file_apps_verifycode_pb_verifycode_proto_goTypes = nil
	file_apps_verifycode_pb_verifycode_proto_depIdxs = nil
}
