// Code generated by protoc-gen-go-http. DO NOT EDIT.

package department

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/keyauth.department.DepartmentService/QueryDepartment",
				FunctionName:     "QueryDepartment",
				Path:             "/departments",
				Method:           "GET",
				Resource:         "department",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{"allow": "*"},
			},
			{
				GrpcPath:         "/keyauth.department.DepartmentService/DescribeDepartment",
				FunctionName:     "DescribeDepartment",
				Path:             "/departments/:id",
				Method:           "POST",
				Resource:         "department",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{"allow": "*"},
			},
			{
				GrpcPath:         "/keyauth.department.DepartmentService/CreateDepartment",
				FunctionName:     "CreateDepartment",
				Path:             "/departments",
				Method:           "POST",
				Resource:         "department",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{"allow": "org_admin"},
			},
			{
				GrpcPath:         "/keyauth.department.DepartmentService/UpdateDepartment",
				FunctionName:     "UpdateDepartment",
				Path:             "/departments/:id",
				Method:           "PUT",
				Resource:         "department",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{"allow": "org_admin"},
			},
			{
				GrpcPath:         "/keyauth.department.DepartmentService/DeleteDepartment",
				FunctionName:     "DeleteDepartment",
				Path:             "/departments/:id",
				Method:           "DELETE",
				Resource:         "department",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{"allow": "org_admin"},
			},
			{
				GrpcPath:         "/keyauth.department.DepartmentService/QueryApplicationForm",
				FunctionName:     "QueryApplicationForm",
				Path:             "/join_apply",
				Method:           "GET",
				Resource:         "department_apply",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{"allow": "org_admin"},
			},
			{
				GrpcPath:         "/keyauth.department.DepartmentService/DescribeApplicationForm",
				FunctionName:     "DescribeApplicationForm",
				Path:             "/join_apply/:id",
				Method:           "GET",
				Resource:         "department_apply",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{"allow": "org_admin"},
			},
			{
				GrpcPath:         "/keyauth.department.DepartmentService/JoinDepartment",
				FunctionName:     "JoinDepartment",
				Path:             "/join_apply/:id",
				Method:           "POST",
				Resource:         "department_apply",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{"allow": "org_admin"},
			},
			{
				GrpcPath:         "/keyauth.department.DepartmentService/DealApplicationForm",
				FunctionName:     "DealApplicationForm",
				Path:             "/join_apply/:id",
				Method:           "PUT",
				Resource:         "department_apply",
				AuthEnable:       true,
				PermissionEnable: false,
				Labels:           map[string]string{"allow": "org_admin"},
			},
		},
	}
	return set
}
