// Code generated by protoc-gen-go-http. DO NOT EDIT.

package department

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:     "/keyauth.department.DepartmentService/QueryDepartment",
				FunctionName: "QueryDepartment",
			},
			{
				GrpcPath:     "/keyauth.department.DepartmentService/DescribeDepartment",
				FunctionName: "DescribeDepartment",
			},
			{
				GrpcPath:     "/keyauth.department.DepartmentService/CreateDepartment",
				FunctionName: "CreateDepartment",
			},
			{
				GrpcPath:     "/keyauth.department.DepartmentService/UpdateDepartment",
				FunctionName: "UpdateDepartment",
			},
			{
				GrpcPath:     "/keyauth.department.DepartmentService/DeleteDepartment",
				FunctionName: "DeleteDepartment",
			},
			{
				GrpcPath:     "/keyauth.department.DepartmentService/QueryApplicationForm",
				FunctionName: "QueryApplicationForm",
			},
			{
				GrpcPath:     "/keyauth.department.DepartmentService/DescribeApplicationForm",
				FunctionName: "DescribeApplicationForm",
			},
			{
				GrpcPath:     "/keyauth.department.DepartmentService/JoinDepartment",
				FunctionName: "JoinDepartment",
			},
			{
				GrpcPath:     "/keyauth.department.DepartmentService/DealApplicationForm",
				FunctionName: "DealApplicationForm",
			},
		},
	}
	return set
}
