// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package role

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseRoleTypeFromString Parse RoleType from string
func ParseRoleTypeFromString(str string) (RoleType, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := RoleType_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown RoleType: %s", str)
	}

	return RoleType(v), nil
}

// Equal type compare
func (t RoleType) Equal(target RoleType) bool {
	return t == target
}

// IsIn todo
func (t RoleType) IsIn(targets ...RoleType) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t RoleType) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *RoleType) UnmarshalJSON(b []byte) error {
	ins, err := ParseRoleTypeFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}

// ParseEffectTypeFromString Parse EffectType from string
func ParseEffectTypeFromString(str string) (EffectType, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := EffectType_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown EffectType: %s", str)
	}

	return EffectType(v), nil
}

// Equal type compare
func (t EffectType) Equal(target EffectType) bool {
	return t == target
}

// IsIn todo
func (t EffectType) IsIn(targets ...EffectType) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t EffectType) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *EffectType) UnmarshalJSON(b []byte) error {
	ins, err := ParseEffectTypeFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
