// Code generated by protoc-gen-go-http. DO NOT EDIT.

package role

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:              "/keyauth.role.RoleService/CreateRole",
				FunctionName:      "CreateRole",
				Method:            "",
				Resource:          "role",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "create"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.role.RoleService/QueryRole",
				FunctionName:      "QueryRole",
				Method:            "",
				Resource:          "role",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "list"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.role.RoleService/DescribeRole",
				FunctionName:      "DescribeRole",
				Method:            "",
				Resource:          "role",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "get"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.role.RoleService/DeleteRole",
				FunctionName:      "DeleteRole",
				Method:            "",
				Resource:          "role",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "delete"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.role.RoleService/QueryPermission",
				FunctionName:      "QueryPermission",
				Method:            "",
				Resource:          "permission",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "list"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.role.RoleService/DescribePermission",
				FunctionName:      "DescribePermission",
				Method:            "",
				Resource:          "permission",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "get"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.role.RoleService/AddPermissionToRole",
				FunctionName:      "AddPermissionToRole",
				Method:            "",
				Resource:          "permission",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "update"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.role.RoleService/RemovePermissionFromRole",
				FunctionName:      "RemovePermissionFromRole",
				Method:            "",
				Resource:          "permission",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "update"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.role.RoleService/UpdatePermission",
				FunctionName:      "UpdatePermission",
				Method:            "",
				Resource:          "permission",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "update"},
				Extension:         map[string]string{},
			},
		},
	}
	return set
}
