// Code generated by protoc-gen-go-http. DO NOT EDIT.

package verifycode

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:     "/keyauth.verifycode.VerifyCodeService/IssueCode",
				FunctionName: "IssueCode",
			},
			{
				GrpcPath:     "/keyauth.verifycode.VerifyCodeService/CheckCode",
				FunctionName: "CheckCode",
			},
		},
	}
	return set
}
