// Code generated by protoc-gen-go-http. DO NOT EDIT.

package token

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:              "/keyauth.token.TokenService/IssueToken",
				FunctionName:      "IssueToken",
				Method:            "POST",
				Resource:          "token",
				AuthEnable:        false,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.token.TokenService/ValidateToken",
				FunctionName:      "ValidateToken",
				Method:            "GET",
				Resource:          "token",
				AuthEnable:        false,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.token.TokenService/DescribeToken",
				FunctionName:      "DescribeToken",
				Method:            "GET",
				Resource:          "token",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.token.TokenService/RevolkToken",
				FunctionName:      "RevolkToken",
				Method:            "DELETE",
				Resource:          "token",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.token.TokenService/BlockToken",
				FunctionName:      "BlockToken",
				Method:            "PUT",
				Resource:          "token",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.token.TokenService/ChangeNamespace",
				FunctionName:      "ChangeNamespace",
				Method:            "PUT",
				Resource:          "token",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.token.TokenService/QueryToken",
				FunctionName:      "QueryToken",
				Method:            "GET",
				Resource:          "token",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.token.TokenService/DeleteToken",
				FunctionName:      "DeleteToken",
				Method:            "GET",
				Resource:          "token",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
		},
	}
	return set
}
