// Code generated by protoc-gen-go-http. DO NOT EDIT.

package application

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:         "/keyauth.application.UserService/CreateUserApplication",
				FunctionName: "CreateUserApplication",
			},
			{
				Path:         "/keyauth.application.UserService/DescribeApplication",
				FunctionName: "DescribeApplication",
			},
			{
				Path:         "/keyauth.application.UserService/QueryApplication",
				FunctionName: "QueryApplication",
			},
			{
				Path:         "/keyauth.application.UserService/DeleteApplication",
				FunctionName: "DeleteApplication",
			},
			{
				Path:         "/keyauth.application.AdminService/CreateBuildInApplication",
				FunctionName: "CreateBuildInApplication",
			},
			{
				Path:         "/keyauth.application.AdminService/GetBuildInApplication",
				FunctionName: "GetBuildInApplication",
			},
		},
	}
	return set
}
