// Code generated by protoc-gen-go-http. DO NOT EDIT.

package application

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:         "/keyauth.application.ApplicationService/CreateApplication",
				FunctionName: "CreateApplication",
			},
			{
				Path:         "/keyauth.application.ApplicationService/DescribeApplication",
				FunctionName: "DescribeApplication",
			},
			{
				Path:         "/keyauth.application.ApplicationService/QueryApplication",
				FunctionName: "QueryApplication",
			},
			{
				Path:         "/keyauth.application.ApplicationService/DeleteApplication",
				FunctionName: "DeleteApplication",
			},
		},
	}
	return set
}
