// Code generated by protoc-gen-go-http. DO NOT EDIT.

package application

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:              "/keyauth.application.UserService/CreateUserApplication",
				FunctionName:      "CreateUserApplication",
				Method:            "POST",
				Resource:          "application",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "domain_admin", "action": "create"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.application.UserService/DescribeApplication",
				FunctionName:      "DescribeApplication",
				Method:            "GET",
				Resource:          "application",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "domain_admin", "action": "get"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.application.UserService/QueryApplication",
				FunctionName:      "QueryApplication",
				Method:            "GET",
				Resource:          "application",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "domain_admin", "action": "list"},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.application.UserService/DeleteApplication",
				FunctionName:      "DeleteApplication",
				Method:            "DELETE",
				Resource:          "application",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "domain_admin", "action": "delete"},
				Extension:         map[string]string{},
			},
			{
				Path:         "/keyauth.application.AdminService/CreateBuildInApplication",
				FunctionName: "CreateBuildInApplication",
			},
			{
				Path:         "/keyauth.application.AdminService/GetBuildInApplication",
				FunctionName: "GetBuildInApplication",
			},
		},
	}
	return set
}
