// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: apps/otp/pb/otp.proto

package otp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OTPStatus int32

const (
	OTPStatus_UNKNOWN  OTPStatus = 0
	OTPStatus_ENABLED  OTPStatus = 1
	OTPStatus_DISABLED OTPStatus = 2
)

// Enum value maps for OTPStatus.
var (
	OTPStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "ENABLED",
		2: "DISABLED",
	}
	OTPStatus_value = map[string]int32{
		"UNKNOWN":  0,
		"ENABLED":  1,
		"DISABLED": 2,
	}
)

func (x OTPStatus) Enum() *OTPStatus {
	p := new(OTPStatus)
	*p = x
	return p
}

func (x OTPStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OTPStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_otp_pb_otp_proto_enumTypes[0].Descriptor()
}

func (OTPStatus) Type() protoreflect.EnumType {
	return &file_apps_otp_pb_otp_proto_enumTypes[0]
}

func (x OTPStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OTPStatus.Descriptor instead.
func (OTPStatus) EnumDescriptor() ([]byte, []int) {
	return file_apps_otp_pb_otp_proto_rawDescGZIP(), []int{0}
}

type OTPAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// OTP密钥
	// @gotags: bson:"_id" json:"secret_key"
	SecretKey string `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key" bson:"_id"`
	// OTP过期时间
	// @gotags: bson:"expired_second" json:"expired_second"
	ExpiredSecond uint64 `protobuf:"varint,2,opt,name=expired_second,json=expiredSecond,proto3" json:"expired_second" bson:"expired_second"`
	// OTP长度
	// @gotags: bson:"digits" json:"digits"
	Digits int32 `protobuf:"varint,3,opt,name=digits,proto3" json:"digits" bson:"digits"`
	// OTP二维码内容
	// @gotags: bson:"otp_code" json:"otp_code"
	OtpCode string `protobuf:"bytes,4,opt,name=otp_code,json=otpCode,proto3" json:"otp_code" bson:"otp_code"`
	// OTP二维码图片地址
	// @gotags: bson:"otp_url" json:"otp_url"
	OtpUrl string `protobuf:"bytes,5,opt,name=otp_url,json=otpUrl,proto3" json:"otp_url" bson:"otp_url"`
	// 用户名
	// @gotags: bson:"account" json:"account"
	Account string `protobuf:"bytes,6,opt,name=account,proto3" json:"account" bson:"account"`
}

func (x *OTPAuth) Reset() {
	*x = OTPAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_otp_pb_otp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OTPAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTPAuth) ProtoMessage() {}

func (x *OTPAuth) ProtoReflect() protoreflect.Message {
	mi := &file_apps_otp_pb_otp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTPAuth.ProtoReflect.Descriptor instead.
func (*OTPAuth) Descriptor() ([]byte, []int) {
	return file_apps_otp_pb_otp_proto_rawDescGZIP(), []int{0}
}

func (x *OTPAuth) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *OTPAuth) GetExpiredSecond() uint64 {
	if x != nil {
		return x.ExpiredSecond
	}
	return 0
}

func (x *OTPAuth) GetDigits() int32 {
	if x != nil {
		return x.Digits
	}
	return 0
}

func (x *OTPAuth) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

func (x *OTPAuth) GetOtpUrl() string {
	if x != nil {
		return x.OtpUrl
	}
	return ""
}

func (x *OTPAuth) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

var File_apps_otp_pb_otp_proto protoreflect.FileDescriptor

var file_apps_otp_pb_otp_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6f, 0x74, 0x70, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x74,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x6b, 0x65, 0x79, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x6f, 0x74, 0x70, 0x22,
	0xb5, 0x01, 0x0a, 0x07, 0x4f, 0x54, 0x50, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x74, 0x70,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x74, 0x70,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x74, 0x70, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x74, 0x70, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x33, 0x0a, 0x09, 0x4f, 0x54, 0x50, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x42, 0x28, 0x5a, 0x26,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6b, 0x65, 0x79, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x70,
	0x70, 0x73, 0x2f, 0x6f, 0x74, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_otp_pb_otp_proto_rawDescOnce sync.Once
	file_apps_otp_pb_otp_proto_rawDescData = file_apps_otp_pb_otp_proto_rawDesc
)

func file_apps_otp_pb_otp_proto_rawDescGZIP() []byte {
	file_apps_otp_pb_otp_proto_rawDescOnce.Do(func() {
		file_apps_otp_pb_otp_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_otp_pb_otp_proto_rawDescData)
	})
	return file_apps_otp_pb_otp_proto_rawDescData
}

var file_apps_otp_pb_otp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_otp_pb_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apps_otp_pb_otp_proto_goTypes = []interface{}{
	(OTPStatus)(0),  // 0: infraboard.keyauth.otp.OTPStatus
	(*OTPAuth)(nil), // 1: infraboard.keyauth.otp.OTPAuth
}
var file_apps_otp_pb_otp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_otp_pb_otp_proto_init() }
func file_apps_otp_pb_otp_proto_init() {
	if File_apps_otp_pb_otp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_otp_pb_otp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OTPAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_otp_pb_otp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_otp_pb_otp_proto_goTypes,
		DependencyIndexes: file_apps_otp_pb_otp_proto_depIdxs,
		EnumInfos:         file_apps_otp_pb_otp_proto_enumTypes,
		MessageInfos:      file_apps_otp_pb_otp_proto_msgTypes,
	}.Build()
	File_apps_otp_pb_otp_proto = out.File
	file_apps_otp_pb_otp_proto_rawDesc = nil
	file_apps_otp_pb_otp_proto_goTypes = nil
	file_apps_otp_pb_otp_proto_depIdxs = nil
}
