// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package otp

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseOTPStatusFromString Parse OTPStatus from string
func ParseOTPStatusFromString(str string) (OTPStatus, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := OTPStatus_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown OTPStatus: %s", str)
	}

	return OTPStatus(v), nil
}

// Equal type compare
func (t OTPStatus) Equal(target OTPStatus) bool {
	return t == target
}

// IsIn todo
func (t OTPStatus) IsIn(targets ...OTPStatus) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t OTPStatus) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *OTPStatus) UnmarshalJSON(b []byte) error {
	ins, err := ParseOTPStatusFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
