// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: apps/otp/pb/request.proto

package otp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateOTPAuthRequest 创建OTP请求
type CreateOTPAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 关联用户
	// @gotags: json:"account" validate:"required"
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account" validate:"required"`
}

func (x *CreateOTPAuthRequest) Reset() {
	*x = CreateOTPAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_otp_pb_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOTPAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOTPAuthRequest) ProtoMessage() {}

func (x *CreateOTPAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_otp_pb_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOTPAuthRequest.ProtoReflect.Descriptor instead.
func (*CreateOTPAuthRequest) Descriptor() ([]byte, []int) {
	return file_apps_otp_pb_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOTPAuthRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// DescribeOTPAuthRequest 查询OTP请求
type DescribeOTPAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 关联用户
	// @gotags: json:"account" validate:"required"
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account" validate:"required"`
}

func (x *DescribeOTPAuthRequest) Reset() {
	*x = DescribeOTPAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_otp_pb_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeOTPAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeOTPAuthRequest) ProtoMessage() {}

func (x *DescribeOTPAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_otp_pb_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeOTPAuthRequest.ProtoReflect.Descriptor instead.
func (*DescribeOTPAuthRequest) Descriptor() ([]byte, []int) {
	return file_apps_otp_pb_request_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeOTPAuthRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// DeleteOTPAuthRequest 删除OTP请求
type DeleteOTPAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 关联用户
	// @gotags: json:"account" validate:"required"
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account" validate:"required"`
}

func (x *DeleteOTPAuthRequest) Reset() {
	*x = DeleteOTPAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_otp_pb_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOTPAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOTPAuthRequest) ProtoMessage() {}

func (x *DeleteOTPAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_otp_pb_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOTPAuthRequest.ProtoReflect.Descriptor instead.
func (*DeleteOTPAuthRequest) Descriptor() ([]byte, []int) {
	return file_apps_otp_pb_request_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteOTPAuthRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// 启用OTP
type EnableOTPAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 关联用户
	// @gotags: json:"account" validate:"required"
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account" validate:"required"`
}

func (x *EnableOTPAuthRequest) Reset() {
	*x = EnableOTPAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_otp_pb_request_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableOTPAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableOTPAuthRequest) ProtoMessage() {}

func (x *EnableOTPAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_otp_pb_request_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableOTPAuthRequest.ProtoReflect.Descriptor instead.
func (*EnableOTPAuthRequest) Descriptor() ([]byte, []int) {
	return file_apps_otp_pb_request_proto_rawDescGZIP(), []int{3}
}

func (x *EnableOTPAuthRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

// 禁用OTP
type DisableOTPAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 关联用户
	// @gotags: json:"account" validate:"required"
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account" validate:"required"`
}

func (x *DisableOTPAuthRequest) Reset() {
	*x = DisableOTPAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_otp_pb_request_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableOTPAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableOTPAuthRequest) ProtoMessage() {}

func (x *DisableOTPAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_otp_pb_request_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableOTPAuthRequest.ProtoReflect.Descriptor instead.
func (*DisableOTPAuthRequest) Descriptor() ([]byte, []int) {
	return file_apps_otp_pb_request_proto_rawDescGZIP(), []int{4}
}

func (x *DisableOTPAuthRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type UpdateOTPStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 关联用户
	// @gotags: json:"account" validate:"required"
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account" validate:"required"`
	// OTP是否开启
	// @gotags: json:"otp_status" validate:"required"
	OtpStatus OTPStatus `protobuf:"varint,2,opt,name=otp_status,json=otpStatus,proto3,enum=infraboard.keyauth.otp.OTPStatus" json:"otp_status" validate:"required"`
}

func (x *UpdateOTPStatusRequest) Reset() {
	*x = UpdateOTPStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_otp_pb_request_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOTPStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOTPStatusRequest) ProtoMessage() {}

func (x *UpdateOTPStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_otp_pb_request_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOTPStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOTPStatusRequest) Descriptor() ([]byte, []int) {
	return file_apps_otp_pb_request_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOTPStatusRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UpdateOTPStatusRequest) GetOtpStatus() OTPStatus {
	if x != nil {
		return x.OtpStatus
	}
	return OTPStatus_UNKNOWN
}

var File_apps_otp_pb_request_proto protoreflect.FileDescriptor

var file_apps_otp_pb_request_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6f, 0x74, 0x70, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6b, 0x65, 0x79, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x6f, 0x74, 0x70, 0x1a, 0x15, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x6f, 0x74, 0x70, 0x2f, 0x70, 0x62,
	0x2f, 0x6f, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x54, 0x50, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x32, 0x0a, 0x16,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x54, 0x50, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x54, 0x50, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x30, 0x0a, 0x14, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x54, 0x50, 0x41,
	0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x31, 0x0a, 0x15, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4f,
	0x54, 0x50, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x74, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x54, 0x50, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x0a, 0x6f,
	0x74, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x21, 0x2e, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6b, 0x65, 0x79,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x6f, 0x74, 0x70, 0x2e, 0x4f, 0x54, 0x50, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x09, 0x6f, 0x74, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6b, 0x65, 0x79, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61,
	0x70, 0x70, 0x73, 0x2f, 0x6f, 0x74, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_otp_pb_request_proto_rawDescOnce sync.Once
	file_apps_otp_pb_request_proto_rawDescData = file_apps_otp_pb_request_proto_rawDesc
)

func file_apps_otp_pb_request_proto_rawDescGZIP() []byte {
	file_apps_otp_pb_request_proto_rawDescOnce.Do(func() {
		file_apps_otp_pb_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_otp_pb_request_proto_rawDescData)
	})
	return file_apps_otp_pb_request_proto_rawDescData
}

var file_apps_otp_pb_request_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apps_otp_pb_request_proto_goTypes = []interface{}{
	(*CreateOTPAuthRequest)(nil),   // 0: infraboard.keyauth.otp.CreateOTPAuthRequest
	(*DescribeOTPAuthRequest)(nil), // 1: infraboard.keyauth.otp.DescribeOTPAuthRequest
	(*DeleteOTPAuthRequest)(nil),   // 2: infraboard.keyauth.otp.DeleteOTPAuthRequest
	(*EnableOTPAuthRequest)(nil),   // 3: infraboard.keyauth.otp.EnableOTPAuthRequest
	(*DisableOTPAuthRequest)(nil),  // 4: infraboard.keyauth.otp.DisableOTPAuthRequest
	(*UpdateOTPStatusRequest)(nil), // 5: infraboard.keyauth.otp.UpdateOTPStatusRequest
	(OTPStatus)(0),                 // 6: infraboard.keyauth.otp.OTPStatus
}
var file_apps_otp_pb_request_proto_depIdxs = []int32{
	6, // 0: infraboard.keyauth.otp.UpdateOTPStatusRequest.otp_status:type_name -> infraboard.keyauth.otp.OTPStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_otp_pb_request_proto_init() }
func file_apps_otp_pb_request_proto_init() {
	if File_apps_otp_pb_request_proto != nil {
		return
	}
	file_apps_otp_pb_otp_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_apps_otp_pb_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOTPAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_otp_pb_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeOTPAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_otp_pb_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOTPAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_otp_pb_request_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableOTPAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_otp_pb_request_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableOTPAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_otp_pb_request_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOTPStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_otp_pb_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_otp_pb_request_proto_goTypes,
		DependencyIndexes: file_apps_otp_pb_request_proto_depIdxs,
		MessageInfos:      file_apps_otp_pb_request_proto_msgTypes,
	}.Build()
	File_apps_otp_pb_request_proto = out.File
	file_apps_otp_pb_request_proto_rawDesc = nil
	file_apps_otp_pb_request_proto_goTypes = nil
	file_apps_otp_pb_request_proto_depIdxs = nil
}
