// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package namespace

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseVisibleFromString Parse Visible from string
func ParseVisibleFromString(str string) (Visible, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := Visible_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown Visible: %s", str)
	}

	return Visible(v), nil
}

// Equal type compare
func (t Visible) Equal(target Visible) bool {
	return t == target
}

// IsIn todo
func (t Visible) IsIn(targets ...Visible) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t Visible) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *Visible) UnmarshalJSON(b []byte) error {
	ins, err := ParseVisibleFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
