// Code generated by protoc-gen-go-http. DO NOT EDIT.

package namespace

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/keyauth.namespace.NamespaceService/CreateNamespace",
				FunctionName:     "CreateNamespace",
				Path:             "/namespaces",
				Method:           "POST",
				Resource:         "namespace",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.namespace.NamespaceService/QueryNamespace",
				FunctionName:     "QueryNamespace",
				Path:             "/namespaces",
				Method:           "GET",
				Resource:         "namespace",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.namespace.NamespaceService/DescribeNamespace",
				FunctionName:     "DescribeNamespace",
				Path:             "/namespaces/:id",
				Method:           "GET",
				Resource:         "namespace",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.namespace.NamespaceService/DeleteNamespace",
				FunctionName:     "DeleteNamespace",
				Path:             "/namespaces/:id",
				Method:           "GET",
				Resource:         "namespace",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
		},
	}
	return set
}
