// Code generated by protoc-gen-go-http. DO NOT EDIT.

package namespace

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:          "/keyauth.namespace.NamespaceService/CreateNamespace",
				FunctionName:      "CreateNamespace",
				Path:              "",
				Method:            "",
				Resource:          "namespace",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "create"},
				Extension:         map[string]string{},
			},
			{
				GrpcPath:          "/keyauth.namespace.NamespaceService/QueryNamespace",
				FunctionName:      "QueryNamespace",
				Path:              "",
				Method:            "",
				Resource:          "namespace",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "list"},
				Extension:         map[string]string{},
			},
			{
				GrpcPath:          "/keyauth.namespace.NamespaceService/DescribeNamespace",
				FunctionName:      "DescribeNamespace",
				Path:              "",
				Method:            "",
				Resource:          "namespace",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          true,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "get"},
				Extension:         map[string]string{},
			},
			{
				GrpcPath:          "/keyauth.namespace.NamespaceService/DeleteNamespace",
				FunctionName:      "DeleteNamespace",
				Path:              "/namespaces/:id",
				Method:            "GET",
				Resource:          "namespace",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{"allow": "perm_admin", "action": "delete"},
				Extension:         map[string]string{},
			},
		},
	}
	return set
}
