// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: app/user/pb/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserType int32

const (
	// 子账号
	UserType_SUB UserType = 0
	// 主账号, 具有本域的所有权限, 为了协助域进行管理,
	// 额外添加了 域管理员/组织管理员/权限管理员/审计管理员, 预留范围 5 ~ 10
	UserType_PRIMARY UserType = 1
	// 审计管理员,
	UserType_AUDIT_ADMIN UserType = 5
	// 组织管理严, 管理该域的 组织结构
	UserType_ORG_ADMIN UserType = 6
	// 权限管理员, 可以为子账号进行授权
	UserType_PERM_ADMIN UserType = 7
	// 域管理员, 有该域的所有管理权限, 协作主账号进行管理
	UserType_DOMAIN_ADMIN UserType = 8
	// 超级管理员, 系统管理员, 万能的人, 不受权限系统约束
	UserType_SUPPER UserType = 15
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0:  "SUB",
		1:  "PRIMARY",
		5:  "AUDIT_ADMIN",
		6:  "ORG_ADMIN",
		7:  "PERM_ADMIN",
		8:  "DOMAIN_ADMIN",
		15: "SUPPER",
	}
	UserType_value = map[string]int32{
		"SUB":          0,
		"PRIMARY":      1,
		"AUDIT_ADMIN":  5,
		"ORG_ADMIN":    6,
		"PERM_ADMIN":   7,
		"DOMAIN_ADMIN": 8,
		"SUPPER":       15,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_user_pb_types_proto_enumTypes[0].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_app_user_pb_types_proto_enumTypes[0]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_app_user_pb_types_proto_rawDescGZIP(), []int{0}
}

var File_app_user_pb_types_proto protoreflect.FileDescriptor

var file_app_user_pb_types_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x70, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x6b, 0x65, 0x79, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2a, 0x6e, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07,
	0x0a, 0x03, 0x53, 0x55, 0x42, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49, 0x4d, 0x41,
	0x52, 0x59, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x55, 0x44, 0x49, 0x54, 0x5f, 0x41, 0x44,
	0x4d, 0x49, 0x4e, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x52, 0x47, 0x5f, 0x41, 0x44, 0x4d,
	0x49, 0x4e, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x45, 0x52, 0x4d, 0x5f, 0x41, 0x44, 0x4d,
	0x49, 0x4e, 0x10, 0x07, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x4f, 0x4d, 0x41, 0x49, 0x4e, 0x5f, 0x41,
	0x44, 0x4d, 0x49, 0x4e, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x55, 0x50, 0x50, 0x45, 0x52,
	0x10, 0x0f, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2f, 0x6b, 0x65, 0x79, 0x61,
	0x75, 0x74, 0x68, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_user_pb_types_proto_rawDescOnce sync.Once
	file_app_user_pb_types_proto_rawDescData = file_app_user_pb_types_proto_rawDesc
)

func file_app_user_pb_types_proto_rawDescGZIP() []byte {
	file_app_user_pb_types_proto_rawDescOnce.Do(func() {
		file_app_user_pb_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_user_pb_types_proto_rawDescData)
	})
	return file_app_user_pb_types_proto_rawDescData
}

var file_app_user_pb_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_user_pb_types_proto_goTypes = []interface{}{
	(UserType)(0), // 0: infraboard.keyauth.user.UserType
}
var file_app_user_pb_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_user_pb_types_proto_init() }
func file_app_user_pb_types_proto_init() {
	if File_app_user_pb_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_user_pb_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_user_pb_types_proto_goTypes,
		DependencyIndexes: file_app_user_pb_types_proto_depIdxs,
		EnumInfos:         file_app_user_pb_types_proto_enumTypes,
	}.Build()
	File_app_user_pb_types_proto = out.File
	file_app_user_pb_types_proto_rawDesc = nil
	file_app_user_pb_types_proto_goTypes = nil
	file_app_user_pb_types_proto_depIdxs = nil
}
