// Code generated by protoc-gen-go-http. DO NOT EDIT.

package tag

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/keyauth.tag.TagService/CreateTag",
				FunctionName:     "CreateTag",
				Path:             "",
				Method:           "",
				Resource:         "",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.tag.TagService/DescribeTag",
				FunctionName:     "DescribeTag",
				Path:             "",
				Method:           "",
				Resource:         "",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.tag.TagService/DeleteTag",
				FunctionName:     "DeleteTag",
				Path:             "",
				Method:           "",
				Resource:         "",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.tag.TagService/QueryTagKey",
				FunctionName:     "QueryTagKey",
				Path:             "",
				Method:           "",
				Resource:         "",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.tag.TagService/QueryTagValue",
				FunctionName:     "QueryTagValue",
				Path:             "",
				Method:           "",
				Resource:         "",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
		},
	}
	return set
}
