// Code generated by protoc-gen-go-http. DO NOT EDIT.

package micro

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:              "/keyauth.micro.MicroService/ValidateClientCredential",
				FunctionName:      "ValidateClientCredential",
				Method:            "POST",
				Resource:          "endpoint",
				AuthEnable:        false,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.micro.MicroService/CreateService",
				FunctionName:      "CreateService",
				Method:            "POST",
				Resource:          "service",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.micro.MicroService/QueryService",
				FunctionName:      "QueryService",
				Method:            "GET",
				Resource:          "service",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.micro.MicroService/DescribeService",
				FunctionName:      "DescribeService",
				Method:            "GET",
				Resource:          "service",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.micro.MicroService/DeleteService",
				FunctionName:      "DeleteService",
				Method:            "DELETE",
				Resource:          "service",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
			{
				Path:              "/keyauth.micro.MicroService/RefreshServiceClientSecret",
				FunctionName:      "RefreshServiceClientSecret",
				Method:            "POST",
				Resource:          "service",
				AuthEnable:        true,
				PermissionEnable:  false,
				AuditLog:          false,
				RequiredNamespace: false,
				Labels:            map[string]string{},
				Extension:         map[string]string{},
			},
		},
	}
	return set
}
