// Code generated by protoc-gen-go-http. DO NOT EDIT.

package micro

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/keyauth.micro.MicroService/ValidateClientCredential",
				FunctionName:     "ValidateClientCredential",
				Path:             "/services/:id/validate",
				Method:           "POST",
				Resource:         "endpoint",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "get"},
			},
			{
				GrpcPath:         "/keyauth.micro.MicroService/CreateService",
				FunctionName:     "CreateService",
				Path:             "/services",
				Method:           "POST",
				Resource:         "service",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "create"},
			},
			{
				GrpcPath:         "/keyauth.micro.MicroService/QueryService",
				FunctionName:     "QueryService",
				Path:             "/services",
				Method:           "GET",
				Resource:         "service",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "list"},
			},
			{
				GrpcPath:         "/keyauth.micro.MicroService/DescribeService",
				FunctionName:     "DescribeService",
				Path:             "/services/:id",
				Method:           "GET",
				Resource:         "service",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "get"},
			},
			{
				GrpcPath:         "/keyauth.micro.MicroService/DeleteService",
				FunctionName:     "DeleteService",
				Path:             "/services/:id",
				Method:           "DELETE",
				Resource:         "service",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "delete"},
			},
			{
				GrpcPath:         "/keyauth.micro.MicroService/RefreshServiceClientSecret",
				FunctionName:     "RefreshServiceClientSecret",
				Path:             "/services/:id/refresh_client_secret",
				Method:           "POST",
				Resource:         "service",
				AuthEnable:       true,
				PermissionEnable: true,
				Labels:           map[string]string{"action": "update"},
			},
		},
	}
	return set
}
