// Code generated by protoc-gen-go-http. DO NOT EDIT.

package micro

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:     "/keyauth.micro.MicroService/ValidateClientCredential",
				FunctionName: "ValidateClientCredential",
			},
			{
				GrpcPath:     "/keyauth.micro.MicroService/CreateService",
				FunctionName: "CreateService",
			},
			{
				GrpcPath:     "/keyauth.micro.MicroService/QueryService",
				FunctionName: "QueryService",
			},
			{
				GrpcPath:     "/keyauth.micro.MicroService/DescribeService",
				FunctionName: "DescribeService",
			},
			{
				GrpcPath:     "/keyauth.micro.MicroService/DeleteService",
				FunctionName: "DeleteService",
			},
			{
				GrpcPath:     "/keyauth.micro.MicroService/RefreshServiceClientSecret",
				FunctionName: "RefreshServiceClientSecret",
			},
		},
	}
	return set
}
