// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package policy

import (
	"bytes"
	"fmt"
	"strings"
)

// ParsePolicyTypeFromString Parse PolicyType from string
func ParsePolicyTypeFromString(str string) (PolicyType, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := PolicyType_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown PolicyType: %s", str)
	}

	return PolicyType(v), nil
}

// Equal type compare
func (t PolicyType) Equal(target PolicyType) bool {
	return t == target
}

// IsIn todo
func (t PolicyType) IsIn(targets ...PolicyType) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t PolicyType) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *PolicyType) UnmarshalJSON(b []byte) error {
	ins, err := ParsePolicyTypeFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
