// Code generated by protoc-gen-go-http. DO NOT EDIT.

package policy

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:         "/keyauth.policy.PolicyService/CreatePolicy",
				FunctionName: "CreatePolicy",
			},
			{
				Path:         "/keyauth.policy.PolicyService/QueryPolicy",
				FunctionName: "QueryPolicy",
			},
			{
				Path:         "/keyauth.policy.PolicyService/DescribePolicy",
				FunctionName: "DescribePolicy",
			},
			{
				Path:         "/keyauth.policy.PolicyService/DeletePolicy",
				FunctionName: "DeletePolicy",
			},
		},
	}
	return set
}
