// Code generated by protoc-gen-go-http. DO NOT EDIT.

package policy

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/keyauth.policy.PolicyService/CreatePolicy",
				FunctionName:     "CreatePolicy",
				Path:             "/policies",
				Method:           "POST",
				Resource:         "policy",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.policy.PolicyService/QueryPolicy",
				FunctionName:     "QueryPolicy",
				Path:             "/policies",
				Method:           "GET",
				Resource:         "policy",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.policy.PolicyService/DescribePolicy",
				FunctionName:     "DescribePolicy",
				Path:             "/policies/:id",
				Method:           "GET",
				Resource:         "policy",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
			{
				GrpcPath:         "/keyauth.policy.PolicyService/DeletePolicy",
				FunctionName:     "DeletePolicy",
				Path:             "/policies/:id",
				Method:           "DELETE",
				Resource:         "policy",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"allow": "perm_admin"},
			},
		},
	}
	return set
}
